[34m[1mwandb[0m: Ctrl + C detected. Stopping sweep.
Exception ignored on calling ctypes callback function: <bound method DataIter._next_wrapper of <xgboost.data.SingleBatchInternalIter object at 0x7f4cfd2c4ca0>>
Traceback (most recent call last):
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/core.py", line 582, in _next_wrapper
    def _next_wrapper(self, this: None) -> int:  # pylint: disable=unused-argument
Exception:
Traceback (most recent call last):
  File "/tmp/ipykernel_65/3695109217.py", line 36, in sweep_train
    model.fit(
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/sklearn.py", line 1580, in fit
    train_dmatrix, evals = _wrap_evaluation_matrices(
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/sklearn.py", line 654, in _wrap_evaluation_matrices
    m = create_dmatrix(
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/sklearn.py", line 1065, in _create_dmatrix
    return QuantileDMatrix(
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/core.py", line 1573, in __init__
    self._init(
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/core.py", line 1634, in _init
    _check_call(ret)
  File "/home/jlai/.local/lib/python3.8/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [23:55:07] /workspace/src/data/iterative_dmatrix.cc:263: Check failed: rbegin == Info().num_row_ (989920 vs. 1979840) :
Stack trace:
  [bt] (0) /home/jlai/.local/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x25c1ac) [0x7f4b67aed1ac]
  [bt] (1) /home/jlai/.local/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x549876) [0x7f4b67dda876]
  [bt] (2) /home/jlai/.local/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x54b99c) [0x7f4b67ddc99c]
  [bt] (3) /home/jlai/.local/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4fb3ea) [0x7f4b67d8c3ea]
  [bt] (4) /home/jlai/.local/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGQuantileDMatrixCreateFromCallback+0x18c) [0x7f4b67a04a5c]
  [bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.7(+0x6ff5) [0x7f4d5ae28ff5]
  [bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.7(+0x640a) [0x7f4d5ae2840a]
  [bt] (7) /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0x5b6) [0x7f4d5ae41316]
  [bt] (8) /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(+0x139ec) [0x7f4d5ae419ec]
