2025-04-14 16:06:09,575 INFO    MainThread:330 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/jlai/ML/wandb/run-20250414_160609-mvulmf0l/logs/debug.log
2025-04-14 16:06:09,575 INFO    MainThread:330 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/jlai/ML/wandb/run-20250414_160609-mvulmf0l/logs/debug-internal.log
2025-04-14 16:06:09,575 INFO    MainThread:330 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f0e06fa7190>
2025-04-14 16:06:09,575 INFO    MainThread:330 [wandb_init.py:init():761] calling init triggers
2025-04-14 16:06:09,575 INFO    MainThread:330 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-14 16:06:09,575 INFO    MainThread:330 [wandb_init.py:init():784] starting backend
2025-04-14 16:06:09,575 INFO    MainThread:330 [wandb_init.py:init():788] sending inform_init request
2025-04-14 16:06:09,577 INFO    MainThread:330 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-14 16:06:09,577 INFO    MainThread:330 [wandb_init.py:init():803] backend started and connected
2025-04-14 16:06:09,582 INFO    MainThread:330 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 16:06:09,582 INFO    MainThread:330 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-14 16:06:09,582 INFO    MainThread:330 [wandb_init.py:init():896] updated telemetry
2025-04-14 16:06:09,584 INFO    MainThread:330 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-14 16:06:09,821 INFO    MainThread:330 [wandb_init.py:init():995] starting run threads in backend
2025-04-14 16:06:10,020 INFO    MainThread:330 [wandb_run.py:_console_start():2377] atexit reg
2025-04-14 16:06:10,020 INFO    MainThread:330 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 16:06:10,020 INFO    MainThread:330 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 16:06:10,020 INFO    MainThread:330 [wandb_run.py:_redirect():2317] Redirects installed.
2025-04-14 16:06:10,021 INFO    MainThread:330 [wandb_init.py:init():1037] run started, returning control to user process
2025-04-14 16:07:07,009 INFO    MainThread:330 [wandb_run.py:_config_callback():1261] config_cb None None {'gamma': 0.487775807119773, 'learning_rate': 0.033344266612338413, 'max_depth': 7, 'n_estimators': 399, 'subsample': 0.894792622158826}
2025-04-14 16:07:08,298 INFO    MainThread:330 [wandb_run.py:_finish():2112] finishing run dlai211/Dark_ph BDT Random/mvulmf0l
2025-04-14 16:07:08,298 INFO    MainThread:330 [jupyter.py:save_history():458] not saving jupyter history
2025-04-14 16:07:08,299 INFO    MainThread:330 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 16:07:08,299 INFO    MainThread:330 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 16:07:08,299 INFO    MainThread:330 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 0
2025-04-14 16:07:08,299 INFO    MainThread:330 [wandb_run.py:_restore():2324] restore
2025-04-14 16:07:08,299 INFO    MainThread:330 [wandb_run.py:_restore():2330] restore done
2025-04-14 16:07:09,638 INFO    MsgRouterThr:330 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-04-14 16:07:09,639 INFO    MainThread:330 [wandb_run.py:_footer_history_summary_info():3958] rendering history
2025-04-14 16:07:09,640 INFO    MainThread:330 [wandb_run.py:_footer_history_summary_info():3990] rendering summary
2025-04-14 16:07:09,642 INFO    MainThread:330 [wandb_run.py:_footer_sync_info():3919] logging synced files
