2025-04-28 00:34:46,441 INFO    MainThread:319 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-04-28 00:34:46,441 INFO    MainThread:319 [wandb_setup.py:_flush():67] Configure stats pid to 319
2025-04-28 00:34:46,441 INFO    MainThread:319 [wandb_setup.py:_flush():67] Loading settings from /home/jlai/.config/wandb/settings
2025-04-28 00:34:46,441 INFO    MainThread:319 [wandb_setup.py:_flush():67] Loading settings from /home/jlai/ML/wandb/settings
2025-04-28 00:34:46,441 INFO    MainThread:319 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-28 00:34:46,441 INFO    MainThread:319 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/jlai/ML/wandb/run-20250428_003446-ecwxbbuc/logs/debug.log
2025-04-28 00:34:46,441 INFO    MainThread:319 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/jlai/ML/wandb/run-20250428_003446-ecwxbbuc/logs/debug-internal.log
2025-04-28 00:34:46,441 INFO    MainThread:319 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f464f752be0>
2025-04-28 00:34:46,442 INFO    MainThread:319 [wandb_init.py:init():761] calling init triggers
2025-04-28 00:34:46,442 INFO    MainThread:319 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-28 00:34:46,442 INFO    MainThread:319 [wandb_init.py:init():784] starting backend
2025-04-28 00:34:46,442 INFO    MainThread:319 [wandb_init.py:init():788] sending inform_init request
2025-04-28 00:34:46,457 INFO    MainThread:319 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-28 00:34:46,458 INFO    MainThread:319 [wandb_init.py:init():803] backend started and connected
2025-04-28 00:34:46,463 INFO    MainThread:319 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-28 00:34:46,464 INFO    MainThread:319 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-28 00:34:46,464 INFO    MainThread:319 [wandb_init.py:init():896] updated telemetry
2025-04-28 00:34:46,465 INFO    MainThread:319 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-28 00:34:46,804 INFO    MainThread:319 [wandb_init.py:init():995] starting run threads in backend
2025-04-28 00:34:46,959 INFO    MainThread:319 [wandb_run.py:_console_start():2377] atexit reg
2025-04-28 00:34:46,960 INFO    MainThread:319 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-28 00:34:46,960 INFO    MainThread:319 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-28 00:34:46,960 INFO    MainThread:319 [wandb_run.py:_redirect():2317] Redirects installed.
2025-04-28 00:34:46,964 INFO    MainThread:319 [wandb_init.py:init():1037] run started, returning control to user process
2025-04-28 00:38:03,484 INFO    MainThread:319 [wandb_run.py:_config_callback():1261] config_cb None None {'gamma': 0.3426754221843381, 'learning_rate': 0.09816026061735678, 'max_depth': 6, 'n_estimators': 312, 'subsample': 0.9382955021894661}
2025-04-28 00:38:04,290 INFO    MainThread:319 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-28 00:38:04,290 INFO    MainThread:319 [wandb_init.py:_pause_backend():564] pausing backend
2025-04-28 00:40:01,364 INFO    MainThread:319 [wandb_init.py:_resume_backend():569] resuming backend
2025-04-28 00:40:05,501 INFO    MainThread:319 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/jlai/ML/wandb/run-20250428_004005-v5czttl9/logs/debug.log
2025-04-28 00:40:05,501 INFO    MainThread:319 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/jlai/ML/wandb/run-20250428_004005-v5czttl9/logs/debug-internal.log
2025-04-28 00:40:05,502 INFO    MainThread:319 [wandb_init.py:init():761] calling init triggers
2025-04-28 00:40:05,502 INFO    MainThread:319 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-28 00:40:05,502 INFO    MainThread:319 [wandb_init.py:init():773] finishing previous run: ecwxbbuc
2025-04-28 00:40:05,502 INFO    MainThread:319 [wandb_run.py:_finish():2112] finishing run dlai211/Dark_ph BDT Random/ecwxbbuc
2025-04-28 00:40:05,502 INFO    MainThread:319 [jupyter.py:save_history():458] not saving jupyter history
2025-04-28 00:40:05,502 INFO    MainThread:319 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-28 00:40:05,502 INFO    MainThread:319 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-28 00:40:05,502 INFO    MainThread:319 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 0
2025-04-28 00:40:05,502 INFO    MainThread:319 [wandb_run.py:_restore():2324] restore
2025-04-28 00:40:05,502 INFO    MainThread:319 [wandb_run.py:_restore():2330] restore done
2025-04-28 00:40:06,952 INFO    MsgRouterThr:319 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-04-28 00:40:06,953 INFO    MainThread:319 [wandb_run.py:_footer_history_summary_info():3958] rendering history
2025-04-28 00:40:06,953 INFO    MainThread:319 [wandb_run.py:_footer_history_summary_info():3990] rendering summary
2025-04-28 00:40:06,955 INFO    MainThread:319 [wandb_run.py:_footer_sync_info():3919] logging synced files
